name: coverage
on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  coverage:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - uses: actions/checkout@v4

      - run: go test -coverprofile=netem.cov -coverpkg=./... ./...

      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: netem.cov
          parallel: true

  finish:
    needs: coverage
    runs-on: ubuntu-22.04
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
